{
    items: [
        {	label:	'Haystack: Building a Customizable Interface for an Information Retrieval System',
            type:	'Publication',
            format:	'6.100 Final Report',
            year:	'1997',
            author: [ 'Mark Asdoorian' ]
        },
        {	label:	'Haystack: A Personal, Intelligent, Indexing System',
            type:	'Publication',
            format:	'Advanced Undergrad Project',
            year:	'1997',
            psURL:	'http://haystack.lcs.mit.edu/papers/haystack.ps.gz',
            psKB:	'68',
            author: [ 'Eytan Adar' ]
        },
        {	label:	'Personalizing Search via Automated Analysis of Interests and Activities',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2005',
            venue:	'SIGIR',
            conferenceURL:	'http://www.sigir2005.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.sigir05.pdf',
            pdfKB:	'102',
            author: [ 'Jaime Teevan', 'Susan Dumais', 'Eric Horvitz' ]
        },
        {	label:	'Thresher: Automating the Unwrapping of Semantic Content from the World Wide Web',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2005',
            venue:	'WWW',
            conferenceURL:	'http://www2005.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/www2005-thresher.pdf',
            pdfKB:	'396',
            author: [ 'Andrew Hogue', 'David Karger' ]
        },
        {	label:	'Magnet: Supporting Navigation in Semistructured Data Environments',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2005',
            venue:	'SIGMOD',
            conferenceURL:	'http://cimic.rutgers.edu/~sigmod05/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/magnet-sigmod2005.pdf',
            pdfKB:	'579',
            author: [ 'Vineet Sinha', 'David Karger' ]
        },
        {	label:	'Haystack: A General Purpose Information Management Tool for End Users of Semistructured Data',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2005',
            venue:	'CIDR',
            conferenceURL:	'http://www-db.cs.wisc.edu/cidr/cidr2005/',
            pdfURL:	'http://www-db.cs.wisc.edu/cidr/cidr2005/papers/P02.pdf',
            author: [ 'David Karger', 'Karun Bakshi', 'David Huynh', 'Dennis Quan', 'Vineet Sinha' ]
        },
        {	label:	'How to Make a Semantic Web Browser',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2004',
            venue:	'WWW',
            conferenceURL:	'http://www.www2004.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/www2004-browser.pdf',
            pdfKB:	'441',
            author: [ 'Dennis Quan', 'David Karger' ]
        },
        {	label:	'The Perfect Search Engine is Not Enough: A Study of Orienteering Behavior in Directed Search',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2004',
            venue:	'CHI',
            conferenceURL:	'http://www.chi2004.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/chi2004-perfectse.pdf',
            pdfKB:	'314',
            author: [ 'Jaime Teevan', 'Christine Alvarado', 'Mark Ackerman', 'David Karger' ]
        },
        {	label:	'Haystack: A Platform for Authoring End User Semantic Web Applications',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'ISWC',
            conferenceURL:	'http://iswc2003.semanticweb.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iswc2003-haystack.pdf',
            pdfKB:	'153',
            author: [ 'Dennis Quan', 'David Huynh', 'David Karger' ]
        },
        {	label:	'Implicit Feedback for Inferring User Preference: A Bibliography',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'SIGIR Forum',
            conferenceURL:	'http://www.acm.org/sigir/forum',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kelly.sigirforum03.pdf',
            pdfKB:	'100',
            author: [ 'Diane Kelly', 'Jaime Teevan' ]
        },
        {	label:	'User Interface Continuations',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'UIST',
            conferenceURL:	'http://www.uist.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/uist2003-uicont.pdf',
            pdfKB:	'111',
            author: [ 'Dennis Quan', 'David Huynh', 'David Karger', 'Robert Miller' ]
        },
        {	label:	'Tackling the Poor Assumptions of Naive Bayes Text Classifiers',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'ICML',
            conferenceURL:	'http://www.hpl.hp.com/conferences/icml03/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/rennie.icml03.ps.gz',
            pdfKB:	'223',
            author: [ 'Jason Rennie', 'Lawrence Shi', 'Jaime Teevan', 'David Karger' ]
        },
        {	label:	'User Interfaces for Supporting Multiple Categorization',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'INTERACT',
            conferenceURL:	'http://www.interact2003.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/interact2003-multicat.pdf',
            pdfKB:	'175',
            author: [ 'Dennis Quan', 'Karun Bakshi', 'David Huynh', 'David Karger' ]
        },
        {	label:	'Empiricial Development of an Exponential Probabilistic Model for Text Retrieval: Using Textual Analysis to Build a Better Model',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'SIGIR',
            conferenceURL:	'http://www.sigir2003.org/',
            psURL:	'http://haystack.lcs.mit.edu/papers/teevan.sigir03.ps',
            psKB:	'339',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.sigir03.pdf',
            pdfKB:	'157',
            author: [ 'Jaime Teevan', 'David Karger' ]
        },
        {	label:	'RDF Authoring Environments for End Users',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'SWFAT',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/swfat2003.pdf',
            pdfKB:	'494',
            author: [ 'Dennis Quan', 'David Karger', 'David Huynh' ]
        },
        {	label:	'Sticky Notes for the Semantic Web',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2003',
            venue:	'IUI',
            conferenceURL:	'http://www.iuiconf.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-annotation.pdf',
            pdfKB:	'88',
            author: [ 'David Karger', 'Boris Katz', 'Jimmy Lin', 'Dennis Quan' ]
        },
        {	label:	'Natural Language Annotations for the Semantic Web',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'2002',
            venue:	'ODBASE',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/odbase02.pdf',
            pdfKB:	'656',
            author: [ 'Boris Katz', 'Jimmy Lin', 'Dennis Quan' ]
        },
        {	label:	'Haystack: Per-User Information Environments',
            type:	'Publication',
            format:	'Conference Paper',
            year:	'1999',
            venue:	'CIKM',
            conferenceURL:	'http://www.acm.org/pubs/contents/proceedings/series/cikm/',
            psURL:	'http://haystack.lcs.mit.edu/papers/cikm99.ps',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/cikm99.pdf',
            author: [ 'Eytan Adar', 'David Karger', 'Lynn Stein' ]
        },
        {	label:	'Haystack: Metadata-Enabled Information Management',
            type:	'Publication',
            format:	'Demo',
            year:	'2003',
            venue:	'UIST',
            conferenceURL:	'http://www.uist.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/uist2003-demo.pdf',
            pdfKB:	'125',
            author: [ 'Dennis Quan', 'David Karger' ]
        },
        {	label:	'Haystack: A Platform for Authoring End User Semantic Web Applications',
            type:	'Publication',
            format:	'Demo',
            year:	'2003',
            event:	'Developer\'s Day',
            venue:	'WWW',
            conferenceURL:	'http://www.www2003.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/www2003-developer.pdf',
            pdfKB:	'20',
            author: [ 'Dennis Quan', 'David Huynh', 'David Karger' ]
        },
        {	label:	'A Unified Abstraction for Messaging on the Semantic Web',
            type:	'Publication',
            format:	'Demo',
            year:	'2003',
            event:	'Developer\'s Day',
            venue:	'WWW',
            conferenceURL:	'http://www.www2003.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/www2003-messaging.pdf',
            pdfKB:	'307',
            author: [ 'Dennis Quan', 'Karun Bakshi', 'David Karger' ]
        },
        {	label:	'User Interaction Experience for Semantic Web Information',
            type:	'Publication',
            format:	'Demo',
            year:	'2003',
            event:	'Developer\'s Day',
            venue:	'WWW',
            conferenceURL:	'http://www.www2003.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/www2003-ui.pdf',
            pdfKB:	'252',
            author: [ 'David Huynh', 'Dennis Quan', 'David Karger' ]
        },
        {	label:	'Haystack: A Platform for Creating, Organizing and Visualizing Semistructured Information',
            type:	'Publication',
            format:	'Demo',
            year:	'2003',
            venue:	'IUI',
            conferenceURL:	'http://www.iuiconf.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-demo.pdf',
            pdfKB:	'97',
            author: [ 'David Huynh', 'David Karger', 'Dennis Quan', 'Vineet Sinha' ]
        },
        {	label:	'Machine Learning on Web Documents',
            type:	'Publication',
            format:	'Doctoral Dissertation',
            year:	'2004',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'Kai Shih' ]
        },
        {	label:	'Designing End User Information Environments Built on Semistructured Data Models',
            type:	'Publication',
            format:	'Doctoral Dissertation',
            year:	'2003',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'Dennis Quan' ]
        },
        {	label:	'Designing Customizable End User Applications Using Semantic Technologies to Improve Information Management',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2006',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-demo.pdf',
            pdfKB:	'97',
            author: [ 'Sumudu Watugala' ]
        },
        {	label:	'Learning the Process of World Wide Web Data Retrieval',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2005',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-demo.pdf',
            pdfKB:	'97',
            author: [ 'Ryan Manuel' ]
        },
        {	label:	'Tools for End-User Creation and Customization of Interfaces for Information Management Tasks',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2004',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-demo.pdf',
            pdfKB:	'97',
            author: [ 'Karun Bakshi' ]
        },
        {	label:	'Tree Pattern Inference and Matching for Wrapper Induction on the World Wide Web',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2004',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2003-demo.pdf',
            pdfKB:	'97',
            author: [ 'Andrew Hogue' ]
        },
        {	label:	'Creating a Web Page Recommendation System for Haystack',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2003',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'Jonathan Derryberry' ]
        },
        {	label:	'A User Interface Framework for Supporting Information Management Tasks in Haystack',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2003',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'David Huynh' ]
        },
        {	label:	'E-mail Classification in the Haystack Framework',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2003',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'Mark Rosen' ]
        },
        {	label:	'Belief Layer for Haystack',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2002',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/kai_shih.phd.pdf',
            pdfKB:	'2122',
            author: [ 'Marina Zhurakhinskaya' ]
        },
        {	label:	'Improving Information Retrieval with Textual Analysis: Bayesian Models',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2001',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.thesis.pdf',
            pdfKB:	'1390',
            author: [ 'Jaime Teevan' ]
        },
        {	label:	'Scan Your Life: Integrating OCR into your Personal Haystack!',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2000',
            psURL:	'http://haystack.lcs.mit.edu/papers/holt.thesis.ps',
            psKB:	'2525',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/holt.thesis.pdf',
            pdfKB:	'774',
            author: [ 'Adam Holt' ]
        },
        {	label:	'Integrating Structural Search Capabilities Into Project Haystack',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2000',
            psURL:	'http://haystack.lcs.mit.edu/papers/svetlana.thesis.ps',
            psKB:	'3520',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/svetlana.thesis.pdf',
            pdfKB:	'374',
            author: [ 'Svetlana Shnitser' ]
        },
        {	label:	'Learning Query Behavior in the Haystack System',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'2000',
            psURL:	'http://haystack.lcs.mit.edu/papers/wchien.thesis.ps',
            psKB:	'2007',
            author: [ 'Wendy Chien' ]
        },
        {	label:	'A Folder-Based Implementation of a Graphical Interface to an Information Retrieval System',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'1999',
            psURL:	'http://haystack.lcs.mit.edu/papers/aidan.thesis.ps',
            psKB:	'3039',
            author: [ 'Aidan Low' ]
        },
        {	label:	'A Data Model for the Haystack Document Management System',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'1999',
            psURL:	'http://haystack.lcs.mit.edu/papers/ilya.thesis.ps',
            psKB:	'1184',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/ilya.thesis.pdf',
            pdfKB:	'535',
            author: [ 'Ilya Lisansky' ]
        },
        {	label:	'Hybrid-Search and Storage of Semi-structured Information',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'1998',
            psURL:	'http://haystack.lcs.mit.edu/papers/Adar.thesis.ps',
            psKB:	'1500',
            author: [ 'Eytan Adar' ]
        },
        {	label:	'Data Manipulation Services in the Haystack IR System',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'1998',
            psURL:	'http://haystack.lcs.mit.edu/papers/Asdoorian.thesis.ps',
            psKB:	'1103',
            author: [ 'Mark Asdoorian' ]
        },
        {	label:	'Agent Based Personalized Information Retrieval',
            type:	'Publication',
            format:	'Master\'s Thesis',
            year:	'1997',
            psURL:	'http://haystack.lcs.mit.edu/papers/kramer-thesis.ps.gz',
            psKB:	'140',
            author: [ 'Joshua Kramer' ]
        },
        {	label:	'The Re:Search Engine: Helping People Return to Information on the Web',
            type:	'Publication',
            format:	'Poster',
            year:	'2005',
            event:	'NSF PIM Workshop',
            conferenceURL:	'http://pim.ischool.washington.edu/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.pim2005.jpg',
            pdfKB:	'264',
            author: [ 'Jaime Teevan' ]
        },
        {	label:	'What is Haystack?',
            type:	'Publication',
            format:	'Presentation',
            year:	'2002',
            event:	'Semantic Web Workshop',
            venue:	'WWW',
            pdfURL:	'http://haystack.lcs.mit.edu/presentations/sww02.ppt',
            pdfKB:	'144',
            author: [ 'David Huynh',
            'Dennis Quan' ]
        },
        {	label:	'The Friendly Semantic Web',
            type:	'Publication',
            format:	'Presentation',
            year:	'2003',
            event:	'Developer\'s Day',
            venue:	'WWW',
            pdfURL:	'http://haystack.lcs.mit.edu/presentations/www2003.ppt',
            pdfKB:	'1081',
            author: [ 'Dennis Quan' ]
        },
        {	label:	'Haystack: A Platform for Creating, Organizing and Visualizing Information Using RDF',
            type:	'Publication',
            format:	'Presentation',
            year:	'2002',
            event:	'Developer\'s Day',
            venue:	'WWW',
            pdfURL:	'http://haystack.lcs.mit.edu/presentations/sww02.ppt',
            pdfKB:	'113',
            author: [ 'David Huynh', 'Dennis Quan' ]
        },
        {	label:	'Basic Concepts for Managing Semi-structured Information in Haystack',
            type:	'Publication',
            format:	'Research Abstract',
            year:	'2002',
            event:	'Student Oxygen Workshop',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sow2002-ontology.pdf',
            pdfKB:	'17',
            author: [ 'Dennis Quan', 'David Huynh', 'Vineet Sinha', 'David Karger', 'Marina Zhurakhinskaya' ]
        },
        {	label:	'Semantic Navigation Through Semi-structured Information',
            type:	'Publication',
            format:	'Research Abstract',
            year:	'2002',
            event:	'Student Oxygen Workshop',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sow2002-semnav.pdf',
            pdfKB:	'37',
            author: [ 'Vineet Sinha', 'Dennis Quan', 'David Huynh', 'David Karger' ]
        },
        {	label:	'Metadata-supported Agent Infrastructure',
            type:	'Publication',
            format:	'Research Abstract',
            year:	'2002',
            event:	'Student Oxygen Workshop',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sow2002-agents.pdf',
            pdfKB:	'16',
            author: [ 'Dennis Quan', 'David Huynh', 'Vineet Sinha', 'David Karger' ]
        },
        {	label:	'Adenine: A Metadata Programming Language',
            type:	'Publication',
            format:	'Research Abstract',
            year:	'2002',
            event:	'Student Oxygen Workshop',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sow2002-adenine.pdf',
            pdfKB:	'18',
            author: [ 'Dennis Quan', 'David Huynh', 'Vineet Sinha', 'David Karger' ]
        },
        {	label:	'The Semantic User Interface Paradigm for Presenting Semi-structured Information',
            type:	'Publication',
            format:	'Research Abstract',
            year:	'2002',
            event:	'Student Oxygen Workshop',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sow2002-ui.pdf',
            pdfKB:	'17',
            author: [ 'David Huynh', 'Dennis Quan', 'Vineet Sinha', 'David Karger' ]
        },
        {	label:	'Displaying Dynamic Information',
            type:	'Publication',
            format:	'Student Poster',
            year:	'2001',
            venue:	'CHI',
            powerpointURL:	'http://haystack.lcs.mit.edu/papers/teevan.chi01.ppt',
            powerpointKB:	'217',
            psURL:	'http://haystack.lcs.mit.edu/papers/teevan.chi01.ps',
            psKB:	'179',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.chi01.pdf',
            pdfKB:	'20',
            author: [ 'Jaime Teevan' ]
        },
        {	label:	'Surviving the Information Explosion: How People Find Their Electronic Information',
            type:	'Publication',
            format:	'Technical Report',
            year:	'2003',
            venue:	'AI Memo',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/alvarado.aim03.pdf',
            pdfKB:	'413',
            author: [ 'Christine Alvarado', 'Jaime Teevan', 'Mark Ackerman', 'David Karger' ]
        },
        {	label:	'How People Re-Find Information When the Web Changes',
            type:	'Publication',
            format:	'Technical Reports',
            year:	'2004',
            venue:	'AI Memo',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.aim04.pdf',
            pdfKB:	'672',
            author: [ 'Jaime Teevan' ]
        },
        {	label:	'Haystack: Per-User Information Environments',
            type:	'Publication',
            format:	'Unpublished Work',
            year:	'1997',
            psURL:	'http://haystack.lcs.mit.edu/papers/karger-stein-9702.ps.gz',
            psKB:	'60',
            author: [ 'David Karger', 'Lynn Stein' ]
        },
        {	label:	'End-User Application Development for the Semantic Web',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2005',
            event:	'Semantic Desktop Workshop',
            venue:	'ISWC',
            conferenceURL:	'http://iswc2005.semanticweb.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/SemDesk-Final.pdf',
            pdfKB:	'1465',
            author: [ 'Karun Bakshi', 'David Karger' ]
        },
        {	label:	'Semantic Web Applications',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2005',
            event:	'End User Semantic Web Interaction Workshop',
            venue:	'ISWC',
            conferenceURL:	'http://iswc2005.semanticweb.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/EndUserInteraction-Final.pdf',
            pdfKB:	'1288',
            author: [ 'Karun Bakshi', 'David Karger' ]
        },
        {	label:	'Beyond the Commons: Investigating the Value of Personalizing Web Search',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2005',
            event:	'Workshop on New Technologies for Personalized Information Access',
            venue:	'PIA',
            conferenceURL:	'http://adiret.cs.uni-magdeburg.de/pia2005/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/teevan.pia2005.pdf',
            pdfKB:	'50',
            author: [ 'Jaime Teevan', 'Susan Dumais', 'Eric Horvitz' ]
        },
        {	label:	'Prerequisites for a Personalizable User Interface',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2004',
            event:	'Workshop on Behavior-based User Interface Customization',
            venue:	'IUI',
            conferenceURL:	'http://www.iuiconf.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/iui2004-adaptiveui.pdf',
            pdfKB:	'154',
            author: [ 'David Karger', 'Dennis Quan' ]
        },
        {	label:	'Wrapper Induction for End-User Semantic Content Development',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2004',
            event:	'Interaction Design and the Semantic Web Workshop',
            venue:	'WWW',
            conferenceURL:	'http://www.www2004.org/',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/idsw2004-wrapperinduction.pdf',
            pdfKB:	'93',
            author: [ 'Andrew Hogue', 'David Karger' ]
        },
        {	label:	'Haystack: A Platform for Creating, Organizing and Visualizing Information Using RDF',
            type:	'Publication',
            format:	'Workshop Paper',
            year:	'2002',
            event:	'Semantic Web Workshop',
            venue:	'WWW',
            pdfURL:	'http://haystack.lcs.mit.edu/papers/sww02.pdf',
            pdfKB:	'310',
            author: [ 'David Huynh', 'David Karger', 'Dennis Quan' ]
        }
    ]
}
