{
    items: [
{ type: 'Politician', label: 'Mitt Romney', party: 'Republican', url: 'http://en.wikipedia.org/wiki/Mitt_Romney', image: 'http://upload.wikimedia.org/wikipedia/en/thumb/0/06/Gov_Romney2HRes.jpg/80px-Gov_Romney2HRes.jpg', text: 'Willard Mitt Romney (b. March 12, 1947) is the 70th Governor of Massachusetts. He is currently in his first term as Governor, serving until 2007. He announced he will not seek re-election in 2006. Romney is frequently mentioned as a possible candidate for the Republican presidential nomination in 2008. He also serves as the chairman of the Republican Governors Association and honorary chairman of the Commonwealth Political Action Committee.' },
{ type: 'Politician', label: 'Don Carcieri', party: 'Republican', url: 'http://en.wikipedia.org/wiki/Don_Carcieri', image: 'http://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Donald_Carcieri_of_Rhode_Island.jpg/80px-Donald_Carcieri_of_Rhode_Island.jpg', text: 'Donald L. "Don" Carcieri (born December 16, 1942) is the governor of the U.S. state of Rhode Island. He is a moderate Republican and has a varied vocational background, having worked as a manufacturing company executive, aid relief worker, bank executive and teacher.' },
{ type: 'Politician', label: 'James H. Douglas', party: 'Republican', url: 'http://en.wikipedia.org/wiki/James_H._Douglas', image: 'http://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Jimdouglas.jpg/80px-Jimdouglas.jpg', text: 'James H. "Jim" Douglas (born June 21, 1951) is an American politician from the U.S. state of Vermont. Douglas is a Republican and currently the Governor of Vermont. Douglas was born in Springfield, Massachusetts. He graduated with a Bachelor of Arts degree from Middlebury College in Middlebury, Vermont, where he had been active in the College Republicans. At Middlebury College, Douglas was a Russian Studies major, and still speaks Russian, even using these skills in establishing a sister-city relationship with Karelia, Russia.' },
{ type: 'Politician', label: 'George E. Pataki', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Robert L. Ehrlich Jr.', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Linda Lingle', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Rod R. Blagojevich', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'M. Jodi Rell', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Arnold Schwarzenegger', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Baldacci', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ruth Ann Minner', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jon Corzine', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Christine Gregoire', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ted Kulongoski', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tim Pawlenty', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jennifer Granholm', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ed Rendell', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Lynch', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim Doyle', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tom Vilsack', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Bill Richardson', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Bob Taft', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kenny Guinn', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jeb Bush', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Bill Owens', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Matt Blunt', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tim Kaine', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mike Huckabee', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Janet Napolitano', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Joe Manchin III', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mike F. Easley', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Phil Bredesen', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kathleen Blanco', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mark Sanford', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Sonny Perdue', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ernie Fletcher', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Haley Barbour', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Brian Schweitzer', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mitchell Daniels', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mike Rounds', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Rick Perry', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Robert Riley', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kathleen Sebelius', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Hoeven', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Frank H. Murkowski', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Brad Henry', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'David Heineman', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim Risch', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Dave Freudenthal', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jon Huntsman', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ted Kennedy', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jack Reed', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Patrick Leahy', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Chuck Schumer', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Paul Sarbanes', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Daniel Inouye', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Richard Durbin', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Christopher Dodd', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Dianne Feinstein', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Olympia Snowe', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Joseph Biden', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jon Corzine', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Patty Murray', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ron Wyden', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mark Dayton', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Carl Levin', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Arlen Specter', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Judd Gregg', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Herb Kohl', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Charles Grassley', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Pete Domenici', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mike DeWine', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Harry Reid', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Bill Nelson', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Wayne Allard', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kit Bond', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Warner', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Blanche Lincoln', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John McCain', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Robert Byrd', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Elizabeth Dole', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Bill Frist', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mary Landrieu', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Lindsey Graham', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Saxby Chambliss', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mitch McConnell', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Thad Cochran', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Max Baucus', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Dick Lugar', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tim Johnson', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kay Hutchison', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Richard Shelby', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Sam Brownback', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Kent Conrad', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ted Stevens', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'James Inhofe', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Chuck Hagel', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Larry Craig', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Craig Thomas', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Orrin Hatch', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Kerry', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Lincoln Chafee', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim Jeffords', party: 'Independent', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Hillary Clinton', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Barbara Mikulski', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Daniel Akaka', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Barack Obama', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Joe Lieberman', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Barbara Boxer', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Susan Collins', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tom Carper', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Frank Lautenberg', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Maria Cantwell', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Gordon Smith', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Norm Coleman', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Debbie Stabenow', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Rick Santorum', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Sununu', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Russell Feingold', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tom Harkin', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jeff Bingaman', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'George Voinovich', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Ensign', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mel Martinez', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ken Salazar', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim Talent', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'George Allen', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Mark Pryor', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jon Kyl', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jay Rockefeller', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Richard Burr', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Lamar Alexander', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'David Vitter', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim DeMint', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Johnny Isakson', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jim Bunning', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Trent Lott', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Conrad Burns', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Evan Bayh', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Thune', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'John Cornyn', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Jeff Sessions', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Pat Roberts', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Byron Dorgan', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Lisa Murkowski', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Tom Coburn', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Ben Nelson', party: 'Democrat', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Michael Crapo', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Michael Enzi', party: 'Republican', url: '', image: '', text: '' },
{ type: 'Politician', label: 'Robert Bennett', party: 'Republican', url: '', image: '', text: '' }
    ]
}
