{
    items: [
        {	type:		'Person',
			label:		'Adam Holt',
            firstName:	'Adam',
            lastName:	'Holt',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Aidan Low',
            firstName:	'Aidan',
            lastName:	'Low',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Andrew Hogue',
            firstName:	'Andrew',
            lastName:	'Hogue',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Boris Katz',
            firstName:	'Boris',
            lastName:	'Katz',
            gender:		'male',
            position:	'research scientist'
        },
        {	type:		'Person',
			label:		'Christine Alvarado',
            firstName:	'Christine',
            lastName:	'Alvarado',
            gender:		'female',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'David Huynh',
            firstName:	'David',
            lastName:	'Huynh',
            gender:		'male',
            position:	'grad student'
        },
        {	type:		'Person',
			label:		'David Karger',
            firstName:	'David',
            lastName:	'Karger',
            gender:		'male',
            position:	'professor'
        },
        {	type:		'Person',
			label:		'Dennis Quan',
            firstName:	'Dennis',
            lastName:	'Quan',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Diane Kelly',
            firstName:	'Diane',
            lastName:	'Kelly',
            gender:		'female',
            position:	'research scientist'
        },
        {	type:		'Person',
			label:		'Eric Horvitz',
            firstName:	'Eric',
            lastName:	'Horvitz',
            gender:		'male',
            position:	'research scientist'
        },
        {	type:		'Person',
			label:		'Eytan Adar',
            firstName:	'Eytan',
            lastName:	'Adar',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Ilya Lisansky',
            firstName:	'Ilya',
            lastName:	'Lisansky',
            gender:		'female',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Jaime Teevan',
            firstName:	'Jaime',
            lastName:	'Teevan',
            gender:		'female',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Jason Rennie',
            firstName:	'Jason',
            lastName:	'Rennie',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Jimmy Lin',
            firstName:	'Jimmy',
            lastName:	'Lin',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Jonathan Derryberry',
            firstName:	'Jonathan',
            lastName:	'Derryberry',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Joshua Kramer',
            firstName:	'Joshua',
            lastName:	'Kramer',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Kai Shih',
            firstName:	'Kai',
            lastName:	'Shih',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Karun Bakshi',
            firstName:	'Karun',
            lastName:	'Bakshi',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Lawrence Shi',
            firstName:	'Lawrence',
            lastName:	'Shi',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Lynn Stein',
            firstName:	'Lynn',
            lastName:	'Stein',
            gender:		'female',
            position:	'professor'
        },
        {	type:		'Person',
			label:		'Marina Zhurakhinskaya',
            firstName:	'Marina',
            lastName:	'Zhurakhinskaya',
            gender:		'female',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Mark Asdoorian',
            firstName:	'Mark',
            lastName:	'Asdoorian',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Mark Rosen',
            firstName:	'Mark',
            lastName:	'Rosen',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Mark Ackerman',
            firstName:	'Mark',
            lastName:	'Ackerman',
            gender:		'male',
            position:	'professor'
        },
        {	type:		'Person',
			label:		'Robert Miller',
            firstName:	'Robert',
            lastName:	'Miller',
            gender:		'male',
            position:	'professor'
        },
        {	type:		'Person',
			label:		'Ryan Manuel',
            firstName:	'Ryan',
            lastName:	'Manuel',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Sumudu Watugala',
            firstName:	'Sumudu',
            lastName:	'Watugala',
            gender:		'female',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Susan Dumais',
            firstName:	'Susan',
            lastName:	'Dumais',
            gender:		'female',
            position:	'research scientist'
        },
        {	type:		'Person',
			label:		'Svetlana Shnitser',
            firstName:	'Svetlana',
            lastName:	'Shnitser',
            gender:		'male',
            position:	'alumni'
        },
        {	type:		'Person',
			label:		'Vineet Sinha',
            firstName:	'Vineet',
            lastName:	'Sinha',
            gender:		'male',
            position:	'grad student'
        },
        {	type:		'Person',
			label:		'Wendy Chien',
            firstName:	'Wendy',
            lastName:	'Chien',
            gender:		'female',
            position:	'alumni'
        }
    ]
}
