{
	"items" : [
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=48",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rivest.jpg",
			"uri" :       "http://128.30.44.24/Ronald+Rivest",
			"last-name" : "Rivest",
			"office" :    "32-G692",
			"phone" :     "253-5880",
			"email" :     "rivest@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Ronald Rivest"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=14",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/fano.jpg",
			"uri" :       "http://128.30.44.24/Robert+Fano",
			"last-name" : "Fano",
			"office" :    "32-G616",
			"phone" :     "253-6021",
			"email" :     "fano@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Robert Fano"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=806",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/indyk.jpg",
			"uri" :       "http://128.30.44.24/Piotr+Indyk",
			"last-name" : "Indyk",
			"office" :    "32-G642",
			"phone" :     "452-3402",
			"email" :     "indyk@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Piotr Indyk"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2005",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/winston.jpg",
			"uri" :       "http://128.30.44.24/Patrick+Winston",
			"last-name" : "Winston",
			"office" :    "32-251",
			"phone" :     "253-6754",
			"email" :     "phw@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Patrick Winston"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=20",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/guttag.jpg",
			"uri" :       "http://128.30.44.24/John+Guttag",
			"last-name" : "Guttag",
			"office" :    "32-G966",
			"phone" :     "253-6022",
			"email" :     "guttag@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "John Guttag"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=55",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/sussman.jpg",
			"uri" :       "http://128.30.44.24/Gerald+Sussman",
			"last-name" : "Sussman",
			"office" :    "32-385",
			"phone" :     "253-5874",
			"email" :     "gjs@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Gerald Sussman"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=75",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/edelman.jpg",
			"uri" :       "http://128.30.44.24/Alan+Edelman",
			"last-name" : "Edelman",
			"office" :    "32-G606",
			"phone" :     "253-1355",
			"email" :     "edelman@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Alan Edelman"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=3",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/berger.jpg",
			"uri" :       "http://128.30.44.24/Bonnie+Berger",
			"last-name" : "Berger",
			"office" :    "32-G574",
			"phone" :     "253-1827",
			"email" :     "bab@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Bonnie Berger"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1525",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/miller.jpg",
			"uri" :       "http://128.30.44.24/Rob+Miller",
			"last-name" : "Miller",
			"office" :    "32-G716",
			"phone" :     "324-6028",
			"email" :     "rcm@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Rob Miller"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2641",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/roy.jpg",
			"uri" :       "http://128.30.44.24/Nicholas+Roy",
			"last-name" : "Roy",
			"office" :    "32-330",
			"phone" :     "253-2517",
			"email" :     "nickroy@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Nicholas Roy"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2016",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/williams.jpg",
			"uri" :       "http://128.30.44.24/Brian+Williams",
			"last-name" : "Williams",
			"office" :    "32-276",
			"phone" :     "253-2739",
			"email" :     "williams@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Brian Williams"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=883",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/stonebraker.jpg",
			"uri" :       "http://128.30.44.24/Michael+Stonebraker",
			"last-name" : "Stonebraker",
			"office" :    "32-G922",
			"phone" :     "253-3538",
			"email" :     "stonebraker@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Michael Stonebraker"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2009",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/kaelbling.jpg",
			"uri" :       "http://128.30.44.24/Leslie+Kaelbling",
			"last-name" : "Kaelbling",
			"office" :    "32-G486",
			"phone" :     "258-9695",
			"email" :     "lpk@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Leslie Kaelbling"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=198",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/devadas.jpg",
			"uri" :       "http://128.30.44.24/Srini+Devadas",
			"last-name" : "Devadas",
			"office" :    "32-G844",
			"phone" :     "253-0454",
			"email" :     "devadas@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Srini Devadas"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2008",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/grimson.jpg",
			"uri" :       "http://128.30.44.24/Eric+Grimson",
			"last-name" : "Grimson",
			"office" :    "32-D524",
			"phone" :     "253-5346",
			"email" :     "welg@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Eric Grimson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1840",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/barzilay.jpg",
			"uri" :       "http://128.30.44.24/Regina+Barzilay",
			"last-name" : "Barzilay",
			"office" :    "32-G468",
			"phone" :     "258-5706",
			"email" :     "regina@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Regina Barzilay"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=30",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/liskov.jpg",
			"uri" :       "http://128.30.44.24/Barbara+Liskov",
			"last-name" : "Liskov",
			"office" :    "32-G942",
			"phone" :     "253-5886",
			"email" :     "liskov@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Barbara Liskov"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2010",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/lozano-perez.jpg",
			"uri" :       "http://128.30.44.24/Tomas+Lozano-Perez",
			"last-name" : "Lozano-Perez",
			"office" :    "32-G492",
			"phone" :     "253-7889",
			"email" :     "tlp@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Tomas Lozano-Perez"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=145",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/amarasinghe.jpg",
			"uri" :       "http://128.30.44.24/Saman+Amarasinghe",
			"last-name" : "Amarasinghe",
			"office" :    "32-G778",
			"phone" :     "253-8879",
			"email" :     "saman@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Saman Amarasinghe"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=17",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/goldwasser.jpg",
			"uri" :       "http://128.30.44.24/Shafi+Goldwasser",
			"last-name" : "Goldwasser",
			"office" :    "32-G682",
			"phone" :     "253-5914",
			"email" :     "shafi@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Shafi Goldwasser"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2003",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/horn.jpg",
			"uri" :       "http://128.30.44.24/Berthold+Horn",
			"last-name" : "Horn",
			"office" :    "32-D434",
			"phone" :     "253-5863",
			"email" :     "bkph@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Berthold Horn"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=479",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/weitzner.jpg",
			"uri" :       "http://128.30.44.24/Daniel+Weitzner",
			"last-name" : "Weitzner",
			"office" :    "32-G516",
			"phone" :     "253-8036",
			"email" :     "djweitzner@w3.org",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Daniel Weitzner"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1175",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/popovic.jpg",
			"uri" :       "http://128.30.44.24/Jovan+Popovic",
			"last-name" : "Popovic",
			"office" :    "32-D534",
			"phone" :     "452-3471",
			"email" :     "jovan@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Jovan Popovic"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=33",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/lynch.jpg",
			"uri" :       "http://128.30.44.24/Nancy+Lynch",
			"last-name" : "Lynch",
			"office" :    "32-G668",
			"phone" :     "253-7225",
			"email" :     "lynch@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Nancy Lynch"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1996",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/shrobe.jpg",
			"uri" :       "http://128.30.44.24/Howard+Shrobe",
			"last-name" : "Shrobe",
			"office" :    "32-225",
			"phone" :     "253-7877",
			"email" :     "hes@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Howard Shrobe"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=892",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/long.jpg",
			"uri" :       "http://128.30.44.24/Bill+Long",
			"last-name" : "Long",
			"office" :    "32-256",
			"phone" :     "253-3508",
			"email" :     "wjl@mit.edu",
			"type" :      "Person",
			"label" :     "Bill Long"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=212",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/arvind.jpg",
			"uri" :       "http://128.30.44.24/Arvind",
			"last-name" : "Arvind",
			"office" :    "32-G866",
			"phone" :     "253-6090",
			"email" :     "arvind@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Arvind"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=56",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/szolovits.jpg",
			"uri" :       "http://128.30.44.24/Peter+Szolovits",
			"last-name" : "Szolovits",
			"office" :    "32-254",
			"phone" :     "253-3476",
			"email" :     "psz@mit.edu",
			"type" :      "Person",
			"label" :     "Peter Szolovits"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2861",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/willsky.jpg",
			"uri" :       "http://128.30.44.24/Alan+Willsky",
			"last-name" : "Willsky",
			"office" :    "32-D582",
			"phone" :     "253-2356",
			"email" :     "willsky@mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Alan Willsky"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=54",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/sollins.jpg",
			"uri" :       "http://128.30.44.24/Karen+Sollins",
			"last-name" : "Sollins",
			"office" :    "32-G818",
			"phone" :     "253-6006",
			"email" :     "sollins@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Karen Sollins"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2000",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/collins.jpg",
			"uri" :       "http://128.30.44.24/Michael+Collins",
			"last-name" : "Collins",
			"office" :    "32-G484",
			"phone" :     "253-0705",
			"email" :     "mcollins@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Michael Collins"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=757",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/ernst.jpg",
			"uri" :       "http://128.30.44.24/Michael+Ernst",
			"last-name" : "Ernst",
			"office" :    "32-G718",
			"phone" :     "253-0945",
			"email" :     "mernst@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Michael Ernst"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2002",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/tidor.jpg",
			"uri" :       "http://128.30.44.24/Bruce+Tidor",
			"last-name" : "Tidor",
			"office" :    "32-212",
			"phone" :     "253-7258",
			"email" :     "tidor@mit.edu",
			"type" :      "Person",
			"label" :     "Bruce Tidor"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=167",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/sudan.jpg",
			"uri" :       "http://128.30.44.24/Madhu+Sudan",
			"last-name" : "Sudan",
			"office" :    "32-G640",
			"phone" :     "253-9680",
			"email" :     "madhu@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Madhu Sudan"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2018",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/brooks.jpg",
			"uri" :       "http://128.30.44.24/Rodney+Brooks",
			"last-name" : "Brooks",
			"office" :    "32-G430",
			"phone" :     "253-5223",
			"email" :     "brooks@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Rodney Brooks"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=301",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/morris.jpg",
			"uri" :       "http://128.30.44.24/Robert+Morris",
			"last-name" : "Morris",
			"office" :    "32-G972",
			"phone" :     "253-5983",
			"email" :     "rtm@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Robert Morris"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=35",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/meyer.jpg",
			"uri" :       "http://128.30.44.24/Albert+R.+Meyer",
			"last-name" : "R. Meyer",
			"office" :    "32-G624",
			"phone" :     "253-6024",
			"email" :     "meyer@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Albert R. Meyer"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=161",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/agarwal.jpg",
			"uri" :       "http://128.30.44.24/Anant+Agarwal",
			"last-name" : "Agarwal",
			"office" :    "32-G782",
			"phone" :     "253-1448",
			"email" :     "agarwal@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Anant Agarwal"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=7",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/clark.jpg",
			"uri" :       "http://128.30.44.24/David+Clark",
			"last-name" : "Clark",
			"office" :    "32-G816",
			"phone" :     "253-6003",
			"email" :     "ddc@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "David Clark"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=953",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/lampson.jpg",
			"uri" :       "http://128.30.44.24/Butler+Lampson",
			"last-name" : "Lampson",
			"office" :    "32-G924",
			"phone" :     "253-6004",
			"email" :     "blampson@microsoft.com",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Butler Lampson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2007",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/adelson.jpg",
			"uri" :       "http://128.30.44.24/Ted+Adelson",
			"last-name" : "Adelson",
			"office" :    [
				"32-D424",
				"46-4115"
			],
			"phone" :     "258-9501",
			"email" :     "adelson@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Ted Adelson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2033",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/knight.jpg",
			"uri" :       "http://128.30.44.24/Thomas+Knight+Jr",
			"last-name" : "Knight",
			"office" :    "32-312",
			"phone" :     "253-7807",
			"email" :     "tk@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Thomas Knight Jr"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2004",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/richards.jpg",
			"uri" :       "http://128.30.44.24/Whitman+Richards",
			"last-name" : "Richards",
			"office" :    "32-364",
			"phone" :     "253-5776",
			"email" :     "wrichards@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Whitman Richards"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1973",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/golland.jpg",
			"uri" :       "http://128.30.44.24/Polina+Golland",
			"last-name" : "Golland",
			"office" :    "32-D470",
			"phone" :     "253-8005",
			"email" :     "polina@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Polina Golland"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=85",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/teller.jpg",
			"uri" :       "http://128.30.44.24/Seth+Teller",
			"last-name" : "Teller",
			"office" :    "32-333",
			"phone" :     "258-7885",
			"email" :     "teller@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Seth Teller"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=235",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/asanovic.jpg",
			"uri" :       "http://128.30.44.24/Krste+Asanovic",
			"last-name" : "Asanovic",
			"office" :    "32-G776",
			"phone" :     "253-8081",
			"email" :     "krste@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Krste Asanovic"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=88",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rudolph.jpg",
			"uri" :       "http://128.30.44.24/Larry+Rudolph",
			"last-name" : "Rudolph",
			"office" :    "32-G868",
			"phone" :     "253-6562",
			"email" :     "rudolph@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Larry Rudolph"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=61",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/ward.jpg",
			"uri" :       "http://128.30.44.24/Steve+Ward",
			"last-name" : "Ward",
			"office" :    "32-G786",
			"phone" :     "253-6036",
			"email" :     "ward@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Steve Ward"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=36",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/micali.jpg",
			"uri" :       "http://128.30.44.24/Silvio+Micali",
			"last-name" : "Micali",
			"office" :    "32-G644",
			"phone" :     "253-5949",
			"email" :     "silvio@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Silvio Micali"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2019",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/fisher.jpg",
			"uri" :       "http://128.30.44.24/John+Fisher",
			"last-name" : "Fisher",
			"office" :    "32-D468",
			"phone" :     "253-0788",
			"email" :     "fisher@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "John Fisher"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=166",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/jackson.jpg",
			"uri" :       "http://128.30.44.24/Daniel+Jackson",
			"last-name" : "Jackson",
			"office" :    "32-G704",
			"phone" :     "258-8471",
			"email" :     "dnj@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Daniel Jackson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=113",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/terman.jpg",
			"uri" :       "http://128.30.44.24/Chris+Terman",
			"last-name" : "Terman",
			"office" :    "32-G790",
			"phone" :     "253-6038",
			"email" :     "cjt@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Chris Terman"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=50",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/seneff.jpg",
			"uri" :       "http://128.30.44.24/Stephanie+Seneff",
			"last-name" : "Seneff",
			"office" :    "32-G438",
			"phone" :     "253-0451",
			"email" :     "seneff@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Stephanie Seneff"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2227",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/madden.jpg",
			"uri" :       "http://128.30.44.24/Sam+Madden",
			"last-name" : "Madden",
			"office" :    "32-G938",
			"phone" :     "258-6643",
			"email" :     "madden@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Sam Madden"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2619",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rubinfeld.jpg",
			"uri" :       "http://128.30.44.24/Ronitt+Rubinfeld",
			"last-name" : "Rubinfeld",
			"office" :    "32-G698",
			"phone" :     "253-0884",
			"email" :     "ronitt@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Ronitt Rubinfeld"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=64",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/zue.jpg",
			"uri" :       "http://128.30.44.24/Victor+Zue",
			"last-name" : "Zue",
			"office" :    "32-G470",
			"phone" :     "253-8513",
			"email" :     "zue@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Victor Zue"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=15",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/garland.jpg",
			"uri" :       "http://128.30.44.24/Stephen+Garland",
			"last-name" : "Garland",
			"office" :    "32-G720",
			"phone" :     "253-1947",
			"email" :     "garland@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Stephen Garland"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=655",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/kaashoek.jpg",
			"uri" :       "http://128.30.44.24/Frans+Kaashoek",
			"last-name" : "Kaashoek",
			"office" :    "32-G992",
			"phone" :     "253-7149",
			"email" :     "kaashoek@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Frans Kaashoek"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=138",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/katabi.jpg",
			"uri" :       "http://128.30.44.24/Dina+Katabi",
			"last-name" : "Katabi",
			"office" :    "32-G936",
			"phone" :     "324-6027",
			"email" :     "dina@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Dina Katabi"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=162",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rinard.jpg",
			"uri" :       "http://128.30.44.24/Martin+Rinard",
			"last-name" : "Rinard",
			"office" :    "32-G744",
			"phone" :     "258-6922",
			"email" :     "rinard@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Martin Rinard"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1183",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/demaine.jpg",
			"uri" :       "http://128.30.44.24/Erik+Demaine",
			"last-name" : "Demaine",
			"office" :    "32-G680",
			"phone" :     "253-6871",
			"email" :     "edemaine@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Erik Demaine"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2011",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/poggio.jpg",
			"uri" :       "http://128.30.44.24/Tomaso+Poggio",
			"last-name" : "Poggio",
			"office" :    [
				"32-D424",
				"46-5177"
			],
			"phone" :     "8-9501/ 3-5230",
			"email" :     "tp@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Tomaso Poggio"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=100",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/wisdom.jpg",
			"uri" :       "http://128.30.44.24/Jack+Wisdom",
			"last-name" : "Wisdom",
			"office" :    "32-386",
			"phone" :     "253-7730",
			"email" :     "wisdom@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Jack Wisdom"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=53",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/sipser.jpg",
			"uri" :       "http://128.30.44.24/Michael+Sipser",
			"last-name" : "Sipser",
			"office" :    "32-G594",
			"phone" :     "253-7877",
			"email" :     "sipser@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Michael Sipser"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2015",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/tenenbaum.jpg",
			"uri" :       "http://128.30.44.24/Joshua+Tenenbaum",
			"last-name" : "Tenenbaum",
			"office" :    [
				"32-G482",
				"46-4015"
			],
			"phone" :     "452-2010",
			"email" :     "jbt@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Joshua Tenenbaum"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2014",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/massaquoi.jpg",
			"uri" :       "http://128.30.44.24/Steve+Massaquoi",
			"last-name" : "Massaquoi",
			"office" :    "32-214",
			"phone" :     "253-7093",
			"email" :     "sgm@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Steve Massaquoi"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=9",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/dennis.jpg",
			"uri" :       "http://128.30.44.24/Jack+Dennis",
			"last-name" : "Dennis",
			"office" :    "32-G864",
			"phone" :     "253-6856",
			"email" :     "dennis@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Jack Dennis"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=38",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/moses.jpg",
			"uri" :       "http://128.30.44.24/Joel+Moses",
			"last-name" : "Moses",
			"office" :    "32-249",
			"phone" :     "253-8592",
			"email" :     "moses@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Joel Moses"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=16",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/glass.jpg",
			"uri" :       "http://128.30.44.24/James+Glass",
			"last-name" : "Glass",
			"office" :    "32-G444",
			"phone" :     "253-1640",
			"email" :     "glass@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "James Glass"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=320",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/gifford.jpg",
			"uri" :       "http://128.30.44.24/Dave+Gifford",
			"last-name" : "Gifford",
			"office" :    "32-G542",
			"phone" :     "253-6039",
			"email" :     "gifford@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Dave Gifford"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2013",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/jaakkola.jpg",
			"uri" :       "http://128.30.44.24/Tommi+Jaakkola",
			"last-name" : "Jaakkola",
			"office" :    "32-G498",
			"phone" :     "253-0440",
			"email" :     "tommi@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Tommi Jaakkola"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=29",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/leiserson.jpg",
			"uri" :       "http://128.30.44.24/Charles+Leiserson",
			"last-name" : "Leiserson",
			"office" :    "32-G768",
			"phone" :     "253-5833",
			"email" :     "cel@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Charles Leiserson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2846",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/stultz.jpg",
			"uri" :       "http://128.30.44.24/Collin+Stultz",
			"last-name" : "Stultz",
			"office" :    "32-310",
			"phone" :     "253-4961",
			"email" :     "cmstultz@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Collin Stultz"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=900034",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/kellis.jpg",
			"uri" :       "http://128.30.44.24/Manolis+Kellis",
			"last-name" : "Kellis",
			"office" :    "32-G564",
			"phone" :     "253-2419",
			"email" :     "manoli@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Manolis Kellis"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2020",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/katz.jpg",
			"uri" :       "http://128.30.44.24/Boris+Katz",
			"last-name" : "Katz",
			"office" :    "32-368",
			"phone" :     "253-6032",
			"email" :     "boris@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Boris Katz"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2017",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/leonard.jpg",
			"uri" :       "http://128.30.44.24/John+Leonard",
			"last-name" : "Leonard",
			"office" :    "32-332",
			"phone" :     "253-0607",
			"email" :     "jleonard@csail.mit.edu",
			"type" :      "Person",
			"label" :     "John Leonard"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2030",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/oreilly.jpg",
			"uri" :       "http://128.30.44.24/Una-May+O%27Reilly",
			"last-name" : "O\'Reilly",
			"office" :    "32-379",
			"phone" :     "253-6437",
			"email" :     "unamay@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Una-May O\'Reilly"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2657",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/shor.jpg",
			"uri" :       "http://128.30.44.24/Peter+Shor",
			"last-name" : "Shor",
			"office" :    "32-G574",
			"phone" :     "253-1827",
			"email" :     "shor@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Peter Shor"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2226",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rus.jpg",
			"uri" :       "http://128.30.44.24/Daniela+Rus",
			"last-name" : "Rus",
			"office" :    "32-374",
			"phone" :     "258-7567",
			"email" :     "rus@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Daniela Rus"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=78",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/abelson.jpg",
			"uri" :       "http://128.30.44.24/Hal+Abelson",
			"last-name" : "Abelson",
			"office" :    "32-386H",
			"phone" :     "253-5856",
			"email" :     "hal@mit.edu",
			"type" :      "Person",
			"label" :     "Hal Abelson"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=49",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/saltzer.jpg",
			"uri" :       "http://128.30.44.24/Jerome+Saltzer",
			"last-name" : "Saltzer",
			"office" :    "32-G922",
			"phone" :     "253-6016",
			"email" :     "saltzer@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Jerome Saltzer"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=74",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/goemans.jpg",
			"uri" :       "http://128.30.44.24/Michel+Goemans",
			"last-name" : "Goemans",
			"office" :    "32-G638",
			"phone" :     "253-2688",
			"email" :     "goemans@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Michel Goemans"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=421",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/durand.jpg",
			"uri" :       "http://128.30.44.24/Fredo+Durand",
			"last-name" : "Durand",
			"office" :    "32-D426",
			"phone" :     "253-7223",
			"email" :     "fredo@graphics.csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Fredo Durand"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2053",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/tedrake.jpg",
			"uri" :       "http://128.30.44.24/Russ+Tedrake",
			"last-name" : "Tedrake",
			"office" :    "32-335",
			"phone" :     "253-1778",
			"email" :     "russt@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Russ Tedrake"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=236",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/balakrishnan.jpg",
			"uri" :       "http://128.30.44.24/Hari+Balakrishnan",
			"last-name" : "Balakrishnan",
			"office" :    "32-G940",
			"phone" :     "253-8713",
			"email" :     "hari@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Hari Balakrishnan"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2012",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/darrell.jpg",
			"uri" :       "http://128.30.44.24/Trevor+Darrell",
			"last-name" : "Darrell",
			"office" :    "32-D512",
			"phone" :     "253-8966",
			"email" :     "trevor@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "Trevor Darrell"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=8",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/corbato.jpg",
			"uri" :       "http://128.30.44.24/F.+J.+Corbato",
			"last-name" : "Corbato",
			"office" :    "32-G616",
			"phone" :     "253-6001",
			"email" :     "corbato@mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "F. J. Corbato"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2006",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/davis.jpg",
			"uri" :       "http://128.30.44.24/Randall+Davis",
			"last-name" : "Davis",
			"office" :    "32-237",
			"phone" :     "253-5879",
			"email" :     "davis@csail.mit.edu",
			"type" :      "Person",
			"label" :     "Randall Davis"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=188",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/berners-lee.jpg",
			"uri" :       "http://128.30.44.24/Tim+Berners-Lee",
			"last-name" : "Berners-Lee",
			"office" :    "32-G524",
			"phone" :     "253-5702",
			"email" :     "timbl@w3.org",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Tim Berners-Lee"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=28",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/leighton.jpg",
			"uri" :       "http://128.30.44.24/Tom+Leighton",
			"last-name" : "Leighton",
			"office" :    "32-G594",
			"phone" :     "253-5876",
			"email" :     "ftl@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "Tom Leighton"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2001",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/freeman.jpg",
			"uri" :       "http://128.30.44.24/William+Freeman",
			"last-name" : "Freeman",
			"office" :    "32-D476",
			"phone" :     "253-8828",
			"email" :     "billf@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Dreyfoos",
			"label" :     "William Freeman"
		},
		{
			"url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=83",
			"photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/karger.jpg",
			"uri" :       "http://128.30.44.24/David+Karger",
			"last-name" : "Karger",
			"office" :    "32-G592",
			"phone" :     "258-6167",
			"email" :     "karger@csail.mit.edu",
			"type" :      "Person",
			"tower" :     "Gates",
			"label" :     "David Karger"
		}
	],
	"types" : {
		"Person" : {
			"uri" : "http://128.30.44.24/Person"
		}
	},
    properties: {
        url: {
            valueType: "url"
        },
        photo: {
            valueType: "url"
        },
        email: {
            valueType: "url"
        }
    }
}